cvm-version: 0.7.3
memory: 65536
cpus: 16
gpus: 1

models:
  - name: "llama3-3-70b-fp8"
    repo: "RedHatAI/Llama-3.3-70B-Instruct-FP8-dynamic@984c96b73bcf6a675945bac6382b9ed551e5d42b"
    mpk: "0d0be05062e4d3fadc17176cffd1ef6b518a02b0410bd897723f423074ec6cb5_72687374336_99f5f660-3ee0-5626-9772-2f082314e763"

containers:
  - name: "llama3-3-70b-fp8"
    image: "vllm/vllm-openai:v0.17.1-cu130@sha256:bbeaaf81ba5704c30f6b87a5df5b10b930d97e916fc98c825d3ad30806e9638b"
    runtime: nvidia
    gpus: all
    ipc: host
    command: [
      "--model", "/tinfoil/mpk/mpk-0d0be05062e4d3fadc17176cffd1ef6b518a02b0410bd897723f423074ec6cb5",
      "--served-model-name", "llama3-3-70b",
      "--enable-auto-tool-choice",
      "--tool-call-parser", "llama3_json",
      "--chat-template", "examples/tool_chat_template_llama3.2_json.jinja",
      "--scheduling_policy", "priority",
      "--port", "8001"
    ]

shim:
  upstream-port: 8001
  authenticated: true
  authenticated-endpoints:
    - /v1/chat/completions
  paths:
    - /v1/chat/completions
    - /metrics
    - /health
